name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.actor == 'trevv16' || github.actor == 'github-actions[bot]'
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
